### ISSUE TITLE
NullInjectorError: No provider for MatDialog

### ISSUE THREAD

**Issue by jmeinlschmidt** [ngneat/effects#62]
### Which @ngneat/effects-* package(s) are the source of the bug?

effects

### Is this a regression?

No

### Description

We've been using [MatDialog](https://material.angular.io/components/dialog/overview) in our effects. However, with this package, we cannot make it work (at least using the standalone API).

When invoking actions, an exception about missing provider is thrown. Is there any way to make this work?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-ybh1gk

### Please provide the exception or error you saw

```true
NullInjectorError: NullInjectorError: No provider for MatDialog!
    at NullInjector.get (core.mjs:8760:27)
    at R3Injector.get (core.mjs:9189:33)
    at R3Injector.get (core.mjs:9189:33)
    at injectInjectorOnly (core.mjs:651:33)
    at ɵɵinject (core.mjs:655:60)
    at inject (core.mjs:738:12)
    at new TodosEffects (todo.effects.ts:11:26)
    at Object.TodosEffects_Factory [as factory] (todo.effects.ts:10:26)
    at R3Injector.hydrate (core.mjs:9290:35)
    at R3Injector.get (core.mjs:9178:33)
```

### Please provide the environment you discovered this bug in

```
elf-effects-matdialog@0.0.0
├── @angular-devkit/build-angular@16.1.4
├── @angular/animations@16.1.4
├── @angular/cdk@16.1.4
├── @angular/cli@16.0.6
├── @angular/common@16.1.4
├── @angular/compiler-cli@16.1.4
├── @angular/compiler@16.1.4
├── @angular/core@16.1.4
├── @angular/forms@16.1.4
├── @angular/material@16.1.4
├── @angular/platform-browser-dynamic@16.1.4
├── @angular/platform-browser@16.1.4
├── @angular/router@16.1.4
├── @ngneat/effects-ng@3.1.3
├── @ngneat/effects@2.1.2
├── @types/jasmine@4.3.5
├── jasmine-core@4.6.0
├── karma-chrome-launcher@3.2.0
├── karma-coverage@2.2.1
├── karma-jasmine-html-reporter@2.0.0
├── karma-jasmine@5.1.0
├── karma@6.4.2
├── rxjs@7.8.1
├── tslib@2.6.0
├── typescript@5.0.4
└── zone.js@0.13.1
```

### Do you want to create a pull request?

No

**Comment by jmeinlschmidt** [comment]
It is not really related to this package. The workaround for me is to provide the missing `MatDialogModule` in `bootstrapApplication` via `importProvidersFrom([MatDialogModule])`.

Working solution here https://stackblitz.com/edit/stackblitz-starters-9yvejp.
